### PR TITLE
Added HTML report for jest tests

### PR DESCRIPTION
**Pull request by martingrossmann**
Added HTML report for jest tests to visualize the results.

### CODE REVIEW

**Comment by conradstrassburger** [comment]
I ran the suite once to check out the report and noticed that `Zombie key doesn't kill living` failed.
I then ran [cache-service.test.ts](https://github.com/T-Systems-MMS/aurelia-components/blob/master/tests/services/cache-service.test.ts) 100 times and noticed 3-4 failures for `Zombie key doesn't kill living` and `Call invalidates other`. 

- [ ] Can you check those as well @martingrossmann?

**Review by conradstrassburger — CHANGES_REQUESTED** [review]
I ran the suite once to check out the report and noticed that `Zombie key doesn't kill living` failed.
I then ran [cache-service.test.ts](https://github.com/T-Systems-MMS/aurelia-components/blob/master/tests/services/cache-service.test.ts) 100 times and noticed 3-4 failures for `Zombie key doesn't kill living` and `Call invalidates other`. 

- [ ] Can you check those as well @martingrossmann?

**Comment by martingrossmann** [comment]
> I ran the suite once to check out the report and noticed that `Zombie key doesn't kill living` failed. I then ran [cache-service.test.ts](https://github.com/T-Systems-MMS/aurelia-components/blob/master/tests/services/cache-service.test.ts) 100 times and noticed 3-4 failures for `Zombie key doesn't kill living` and `Call invalidates other`.
> 
> * [ ]  Can you check those as well @martingrossmann?

Hm... cannot reproduce that but I assume that there is sometimes a timing problem, which depends on the environment. The test uses very short time values.

**Review by conradstrassburger — APPROVED** [review]

**Comment by conradstrassburger** [comment]
Zombie key thing may be revisited in the Future (TM)

**Pull request merged**
